In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [5]:
colnames=['Class', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13']
data = pd.read_csv("wine.data",names = colnames)
data

Class     F1    F2    F3    F4   F5    F6    F7    F8    F9    F10   F11  \
0        1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1        1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2        1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3        1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4        1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..     ...    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173      3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174      3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175      3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176      3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177      3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

      F12   F13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [6]:
y = data.iloc[:, 0].values 
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [7]:
data.drop(['Class'], axis=1, inplace=True)
data

F1    F2    F3    F4   F5    F6    F7    F8    F9    F10   F11   F12  \
0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04  3.92   
1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05  3.40   
2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03  3.17   
3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86  3.45   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04  2.93   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   ...   
173  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64  1.74   
174  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70  1.56   
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61  1.60   

      F13  
0    1065  
1    1050  
2    1185  
3    1480  
4     735  
..    ...  
173   740  
174   750  
175   835  
176   840  
177   560  

[178 rows x 13 columns]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size = 0.3, random_state = 0)

In [9]:
def confusion_metrics (conf_matrix):
# save confusion matrix and slice into four pieces
    TP = conf_matrix[0][0]
    TN = conf_matrix[1][1] + conf_matrix[2][1] + conf_matrix[1][2] + conf_matrix[2][2]
    FP = conf_matrix[0][1] + conf_matrix[0][2]
    FN = conf_matrix[1][0] + conf_matrix[2][0]
    
    # calculate accuracy
    conf_accuracy = (float (TP+TN) / float(TP + TN + FP + FN))
    
    # calculate error rate
    conf_error = 1- conf_accuracy
    
    # calculate the sensitivity
    conf_sensitivity = (TP / float(TP + FN))
    # calculate the specificity
    conf_specificity = (TN / float(TN + FP))
      
    print(f'Accuracy: {round(conf_accuracy,2)}') 
    print(f'Mis-Classification: {round(conf_error,2)}') 
    print(f'Sensitivity: {round(conf_sensitivity,2)}') 
    print(f'Specificity: {round(conf_specificity,2)}')

###Quadratic Kernel SVM

In [10]:
classifier = SVC(kernel = 'poly', degree=2, random_state = 42)
classifier.fit(X_train, y_train)

SVC(degree=2, kernel='poly', random_state=42)

In [11]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 3, 2, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 3, 3, 1, 2, 2,
       2, 3, 2, 1, 1, 1, 2, 2, 3, 2], dtype=int64)

In [12]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[15,  0,  4],
       [ 1, 21,  0],
       [ 1,  9,  3]], dtype=int64)

In [13]:
print(confusion_metrics(cm))

Accuracy: 0.89
Mis-Classification: 0.11
Sensitivity: 0.88
Specificity: 0.89
None


###Radial Basis SVM

In [14]:
classifier = SVC(kernel = 'rbf', random_state = 42)
classifier.fit(X_train, y_train)

SVC(random_state=42)

In [15]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 3, 2, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       3, 2, 3, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 3, 2, 2, 3, 1, 1, 2, 2,
       2, 1, 3, 1, 1, 1, 2, 2, 3, 2], dtype=int64)

In [16]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[17,  0,  2],
       [ 1, 20,  1],
       [ 1,  7,  5]], dtype=int64)

In [17]:
print(confusion_metrics(cm))

Accuracy: 0.93
Mis-Classification: 0.07
Sensitivity: 0.89
Specificity: 0.94
None
